### ISSUE TITLE
Question regarding fail safes

### ISSUE THREAD

**Issue by tomdertech** [OpenTrons/opentrons-api#77]
Hi,

This is a very interesting project. I have been studying the API code and trying to figure out how everything fits together - I am getting there :-)

My question is does the machine `wait` for one action to be completed as "expected" before proceeding with the next? I saw this:

``` python
    def wait_for_arrival(self, tolerance=0.1):

        arrived = False

        coords = self.get_position()

        while not arrived:

            coords = self.get_position()

            diff = {}

            for axis in coords.get('target', {}):

                diff[axis] = coords['current'][axis] - coords['target'][axis]



            dist = pow(diff['x'], 2) + pow(diff['y'], 2) + pow(diff['z'], 2)

            dist_head = math.sqrt(dist)



            """

            smoothie not guaranteed to be EXACTLY where it's target is

            but seems to be about +-0.05 mm from the target coordinate

            the robot's physical resolution is found with:

            1mm / config_steps_per_mm

            """

            if dist_head < tolerance:

                if abs(diff['a']) < tolerance and abs(diff['b']) < tolerance:

                    arrived = True

            else:

                arrived = False

        return arrived
```

which is a case in point. If `arrived = False` then obviously the `while` loop would be exited. I could not see where this method was called at the higher level, what happens if the position never can be reached? I presume there is a "try a number of times" parameter and the main "instruction queue" is exited and the user notified?

Many Thanks.
Regards,
Tom

**Comment by astaff** [comment]
Thanks for your question, Tom. This method is used by `move_head` and `move_plunger`. Since move commands can take long time to finish, in `move_head` we are splitting the trajectory of the head into smaller intervals and are sending the next move command to the smoothieboard a few seconds before it arrives to the destination point from the previous command. Doing this we spend less time waiting for smoothie to return on a single call and can pause the execution on the API level without having to pause/resume smoothieboard directly, which requires disengaging the motors which might lead to losing precision. With this approach, API will not send the next move command until the previous one is finished. A typical scenario would be for the protocol to be executed from a different thread and stop/pause command being sent to it when needed. We will be adding failsafe features as the API evolves.
